# Generated by Django 6.0.5 on 2026-05-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_ar',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_de',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='summary_fr',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ar',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_de',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
