# Generated by Django 6.0.5 on 2026-05-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_body_ar_post_body_de_post_body_en_post_body_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='assets/images/uploads/images/'),
        ),
    ]
