# Generated by Django 6.0.5 on 2026-05-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_images_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
