"""
Django settings for alhosseini project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.templatetags.i18n import language
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@ai%$ip)pb4(%$krtk3iz8)eedaxwb84m8stqp@l-h*b4v14l3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    # UnFold Admin
    'unfold',

    # default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # installed apps
    'rosetta',
    'modeltranslation',
    'django_render_partial',
    'imagekit',
    'ckeditor',
    'ckeditor_uploader',

    #     internal apps
    'App',
    'user',
    'posts',
    # 'comments',
    'courses',
    'categories',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # language
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'alhosseini.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'ckeditor/widget.html'
        ]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alhosseini.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 'ENGINE': 'django.db.backends.postgresql',
        # 'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': BASE_DIR / 'DB/database.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'user.User'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGES = [
    ('en', 'English'),
    ('fr', 'French'),
    ('ar', 'Arabic'),
    ('de', 'Germany'),
    # ('fa', 'Farsi'),
]

ROSETTA_LANGUAGES = LANGUAGES

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_TZ = True

USE_I18N = True
USE_L10N = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'assets/'

STATICFILES_DIRS = [
    BASE_DIR / 'assets'
]

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

CKEDITOR_BASEPATH = "/assets/ckeditor/ckeditor/"

CKEDITOR_UPLOAD_PATH = "media/uploads/ckeditor/"

CKEDITOR_RESTRICT_BY_USER = True

CKEDITOR_ALLOW_NONIMAGE_FILES = False

CKEDITOR_CONFIGS = {
    'default': {
        'width': '100%',
        'height': 'auto',

        'toolbar': 'Custom',

        'toolbar_Custom': [
            ['Format'],

            ['Bold', 'Italic', 'Underline'],

            ['NumberedList', 'BulletedList'],

            ['Link', 'Unlink'],

            ['Image', 'Table', 'HorizontalRule'],

            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],

            ['Undo', 'Redo'],

            ['Source'],

            ['Maximize']
        ],

        'extraPlugins': ','.join([
            'uploadimage',
            'autogrow',
        ]),

        # 'removePlugins': 'stylesheetparser',

        'autoGrow_minHeight': 300,
        'autoGrow_maxHeight': 800,

        'contentsCss': [
            '/assets/css/editor.css',
        ],
    }
}
UNFOLD = {
    "SITE_TITLE": "Alhosseini",
    "SITE_HEADER": "Alhosseini.com",
    "SITE_SUBHEADER": "by Seyed Ali Alhosseini",
    "SITE_DROPDOWN": [
        {
            "icon": "A",
            "title": "alhosseini.com",
            "link": "/",
        },
    ],
}
