# Generated by Django 6.0.5 on 2026-05-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('url', models.TextField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
