# Generated by Django 6.0.5 on 2026-05-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_students_alter_course_teacher'),
        ('posts', '0005_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, to='posts.videos'),
        ),
    ]
