# Generated by Django 6.0.5 on 2026-05-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permissions',
            new_name='permission',
        ),
    ]
